### ISSUE TITLE
Front table polish

### ISSUE THREAD

**Issue by sesam** [dai-shi/will-this-react-global-state-work-in-concurrent-rendering#44]
Good stuff here! In the table, is there some sorting done for the rows? Maybe they show in order of execution of the tests run in the background?

In the table, numbers 1-6 are related to the text above. Maybe it's worth to mark up the table a bit more? Looks like Github markdown tables are minimal, but it should let through HTML, so maybe there's a route to mark up the numbers 1-4 as relating to that hook, and 5-6 as being experimental, so maybe also less important.

If you want to keep things clean, this trick https://stackoverflow.com/a/48170118/296639 helps with adding color using just `~` or `*` around some part of the text 😉

**Comment by dai-shi** [comment]
Thanks for the suggestion.
Hm, I'm not sure if I understand the suggestion fully.
Would you like to show a concrete example? maybe a PR?

Not directly related to this, but I wish we can generate the table from the raw output. Maybe with a small script.

**Comment by dai-shi** [comment]
Closing, but suggestions and contributions to polish the table are welcome.
