### ISSUE TITLE
unstable_enableVersionedWrite info?

### ISSUE THREAD

**Issue by salvoravida** [dai-shi/will-this-react-global-state-work-in-concurrent-rendering#57]
Hi there!
great work!

I'm curious, where I can find more code about unstable_enableVersionedWrite ?

I founded this:

    if (unstable_enableVersionedWrite) {
      scopeContainerRef.current.w = (write) => {
        setVersion((parentVersion) => {
          const nextVersion = parentVersion ? { p: parentVersion } : {};
          write(nextVersion);
          return nextVersion;
        });
      };
    }

**Comment by dai-shi** [comment]
https://github.com/pmndrs/jotai/pull/854
Note that this is highly experimental.

Closing, but feel free to comment here.
