### ISSUE TITLE
Add `nanostores` to the comparison

### ISSUE THREAD

**Issue by vasilii-kovalev** [dai-shi/will-this-react-global-state-work-in-concurrent-rendering#59]
Repository: [nanostores/nanostores](https://github.com/nanostores/nanostores).

CC @ai.

Maybe it would be also useful to add it to https://github.com/dai-shi/lets-compare-global-state-with-react-hooks.

**Comment by dai-shi** [comment]
Feel free to fork and try!

We need to update https://github.com/dai-shi/lets-compare-global-state-with-react-hooks too, which is not actively maintained lately. But, keeping this updated is the plan to go.

Closing, but feel free to add some comments.
