### ISSUE TITLE
Tearing on update test failed

### ISSUE THREAD

**Issue by oleggrishechkin** [dai-shi/will-this-react-global-state-work-in-concurrent-rendering#66]
Hi, @dai-shi 

This is not an issue, but I see some strange behavior.

I'm testing my libs (external stores with useSyncExternalStore and batching via Promise.resolve()). I didn't see any tearing - all counters the same while test, but test failed. 

If I notify subscribers synchronously - test will be succeed. If I change store value in microtask (at the same moment when I notify subscribers) - test will be succeed.

Should I trust test results or my eyes?

**Comment by dai-shi** [comment]
Hi, thanks for using the tool.

In general, do not fully trust the tool.

That said, if you stably see the failed test result, I would assume you can reproduce it with your hands and eyes.
